<a href="https://colab.research.google.com/github/KarlaJazmin123/Practica01/blob/main/Edades.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Titulo
Subtitulo

#Funciones estadísticas

In [2]:
import numpy as np

In [7]:
#Lista de edades
edades=np.array([22,21,20,21,21,21,21,21,21,20,21,21,22,21])
print(edades)
edades

[22 21 20 21 21 21 21 21 21 20 21 21 22 21]


array([22, 21, 20, 21, 21, 21, 21, 21, 21, 20, 21, 21, 22, 21])

In [4]:
#Lista de estaturas
estaturas=np.array([1.79, 1.66, 1.75, 167, 1.76, 1.55, 1.60, 1.73, 1.82, 1.65, 1.61, 1.72, 1.72, 1.62])
print(estaturas)

estaturas

[  1.79   1.66   1.75 167.     1.76   1.55   1.6    1.73   1.82   1.65
   1.61   1.72   1.72   1.62]


array([  1.79,   1.66,   1.75, 167.  ,   1.76,   1.55,   1.6 ,   1.73,
         1.82,   1.65,   1.61,   1.72,   1.72,   1.62])

In [8]:
#Obtener medidas de tendencia central (media y mediana)y
#Medidas de dispersión(Varianza y desviacion estándar)
print("Media del array edades: ", np.mean(edades))
print("Mediana array edades: ", np.median(edades))
print("varianza del array edades: ", np.var(edades))
print("Deviacion estandar del arreglo edades: ", np.std(edades))


Media del array edades:  21.0
Mediana array edades:  21.0
varianza del array edades:  0.2857142857142857
Deviacion estandar del arreglo edades:  0.5345224838248488
